site_name: Fender-Bender
site_url: https://fender-bender.readthedocs.io/
theme:
  name: material
  features:
    - navigation.instant
    - navigation.expand
    - navigation.path
    - toc.integrate
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      toc_depth: 3
nav:
  - Overview: index.md
  - Components Overview: components.md
  - Part Selector Tool: selection_tool.md
  - Printing Guide: printing.md
  - Assembly:
    - Filament Bracket Assembly : assembly/filament_bracket.md
    - Wall Assembly : assembly/walls.md
    - Frame Assembly : assembly/frame.md
  - Installation & Usage: usage.md
  - Building a Custom Configuration: config.md
  - Developer's Overview:
    - Build123d framework: developers_guide/build123d.md
    - The Partomatic Philosophy: developers_guide/partomatic.md
    - BenderConfig: developers_guide/BenderConfig.md
    - Creating New Parts: developers_guide/newparts.md
    - Updating build.py: developers_guide/build.md
