site_name: Fender-Bender
site_url: https://fender-bender.readthedocs.io/
theme:
  name: material
  features:
    - navigation.instant
    - navigation.expand
    - navigation.path
    - toc.integrate
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
nav:
  - Overview: index.md
  - Components Overview: components.md
  - Printing Guide: printing.md
  - Assembly:
    - Filament Bracket Assembly : assembly/filament_bracket.md
    - Wall Assembly : assembly/walls.md
    - Frame Assembly : assembly/frame.md
  - Installation & Usage: usage.md
  - Building a Custom Configuration: config.md
  - Developer's Overview: developers.md