## SEE BOTTOM FOR NOTES

######### Default Configuration #########
[BankConfig]

## MOST LIKELY preferences to adjust
# output path for generated STL files
stl_folder=../stl/prototype

# control how many filament brackets can be loaded into the system
# for the Prusa MMU3, set to 5
filament_count = 3
# thickness of the walls separating the filament chambers
wall_thickness = 3
# the frame style, can be HANGING, STANDING, or HYBRID
# HANGING, adds a wall mount to the back of the frame,
# STANDING, adds a flat stand to the bottom of the frame,
# HYBRID, adds both a wall mount and a stand
frame_style = STANDING
# the method of locking the frame together, can be CLIP, PIN, BOTH, or NONE
frame_lock_style = BOTH

## General specifications
# thickness for parts bearing structural elements
minimum_structural_thickness = 4
# thickness for parts bearing no structural elements
minimum_thickness = 1
# if you need to enforce a certain bracket depth so you can use multiple configuration brackets
# in the same frame, you can set this to the largest number required
# set to -1 to ignore
minimum_bracket_depth = -1

# higher numbers result in a smaller rounding radius for edges
fillet_ratio = 4
# extra gap allowance between parts, adjust as needed for your printer
tolerance = 0.2

## wheel specifications
# diameter of the wheel, increasing will add to the size of the bracket,
# but may work better with certain materials
wheel_diameter = 70
# number of spokes on the wheel, can be adjusted to increase strength or change appearance
wheel_spoke_count = 5
# how much "wiggle" the wheel has. increasing to mach may result in filament getting stuck between the wheel and the bracket
wheel_lateral_tolerance = 0.6
# how much of a gap to allow between the radius of the wheel and the bracket, adjust if needed for your printer (unlikely)
wheel_radial_tolerance = 0.2

## bearing details
bearing_diameter = 12.1
bearing_inner_diameter = 6.1
bearing_shelf_diameter = 8.5
bearing_depth = 4

## filament tube details
tube_inner_diameter = 3.5
tube_outer_diameter = 6.5

## Information about the filament tube connector
connector_diameter = 6.5
connector_length = 6.7
connector_threaded = False
connector_thread_pitch = 1
connector_thread_angle = 30
connector_thread_interference = 0.4


#how deep you want the overall assembled frame to be (needs to be large enough to fully contain the buffered filament)
frame_chamber_depth = 340
# setting to False is recommended, allows you to see into the chambers for better filament management
solid_walls = False
# the sizing for the empty space of the hexagon pattern, larger numbers increase visibility and decrease the strength of the walls
wall_window_apothem = 8
# the sizing for the bars of, larger numbers decrease visibility but increase the strength of the walls
wall_window_bar_thickness = 1.5

frame_tongue_depth = 4
# you may want to make the locking pin a little more loose (larger number here) to make the pin
# easier to insert and remove
frame_lock_pin_tolerance = 0.35

# how far up the filament bracket to place the frame clip with the "CLIP style" frame lock
frame_clip_depth_offset = 10

## detals for the wall bracket
wall_bracket_screw_radius = 2.25
wall_bracket_screw_head_radius = 4.5
wall_bracket_screw_head_sink = 1.4
## how many interlocking elements to add to the wall bracket
wall_bracket_post_count = 3


#### Notes ####

# generally the first four elements should be the most likely things you may wish to adjust
# I've worked to minimize the number of things directly controlled in the configuration file
# many other settings are derived from these values; calculations are in bank_config.py
# adjusting these settings with care and reason *should* result in a working part, but
# there are no guarantees.  If you encounter issues, please open an issue on the github page
